name: Example Workflow

# Diffblue Cover CI responds to pull request
on:
  pull_request:

# Avoid running the same workflow on the same branch concurrently
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  DiffblueCover:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository with permission to push
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # The default GITHUB_TOKEN doesn't have the necessary permissions
          # so a custom token should be used here with sufficient access.
          #
          # Must have access to the project with at least Write role, and scopes
          # including code, commit-statuses, pull-requests, workflows and actions.
          #
          token: ${{ secrets.DIFFBLUE_ACCESS_TOKEN }}

      # Run Diffblue Cover
      - name: Diffblue Cover
        uses: diffblue/cover-github-action@tigers/TG-21006-release-testing
        env:
          JVM_ARGS: -Xmx4096m
          GITHUB_PR_NUMBER: ${{ github.event.number }}
        with:
          # The access token used to push commits and call GitHub APIs.
          #
          # Must have access to the project with at least Write role, and scopes
          # including code, commit-statuses, pull-requests, workflows and actions.
          access-token: ${{ secrets.DIFFBLUE_ACCESS_TOKEN }}

          # The license key provided in your welcome email or provided by your organization.
          # Alternatively obtain a free trial key from https://www.diffblue.com/try-cover/github.
          license-key: ${{ secrets.DIFFBLUE_LICENSE_KEY }}

          # Working directory where the project can be found, if not at the root.
          # working-directory: path/to/project

          # The Diffblue Cover commands and options to use.
          # args: >-
          #   ci
          #   activate
          #   build
          #   validate
          #   create

      # Collect Diffblue Cover log files
      - name: Diffblue Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            **/.diffblue/**
